# Generated by Django 6.1 on 2026-08-31 16:54

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, upload_to=comments.models.attachment_path),
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment_kind',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('text', 'Text')], max_length=5),
        ),
    ]
