# Generated by Django 6.1 on 2026-09-02 08:17

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=comments.models.avatar_path),
        ),
    ]
